// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQPnZUt5WXvzytPT0MHc5l8DbeYXEXwhw',
    appId: '1:719078466525:web:2af8bfad16364e3f33cc34',
    messagingSenderId: '719078466525',
    projectId: 'dar-almeqdad-manegment',
    authDomain: 'dar-almeqdad-manegment.firebaseapp.com',
    storageBucket: 'dar-almeqdad-manegment.firebasestorage.app',
    measurementId: 'G-V1JD7BK8XQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxVw6C9XfjSYOi7cTSTDFYp50CV57qZSI',
    appId: '1:719078466525:android:e8c464e5b20712cf33cc34',
    messagingSenderId: '719078466525',
    projectId: 'dar-almeqdad-manegment',
    storageBucket: 'dar-almeqdad-manegment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA64NvFE1LQOSpddwZofvr7OykKKWkTw6Y',
    appId: '1:719078466525:ios:a8e6f29db40680d233cc34',
    messagingSenderId: '719078466525',
    projectId: 'dar-almeqdad-manegment',
    storageBucket: 'dar-almeqdad-manegment.firebasestorage.app',
    iosBundleId: 'com.example.libraryManagment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA64NvFE1LQOSpddwZofvr7OykKKWkTw6Y',
    appId: '1:719078466525:ios:a8e6f29db40680d233cc34',
    messagingSenderId: '719078466525',
    projectId: 'dar-almeqdad-manegment',
    storageBucket: 'dar-almeqdad-manegment.firebasestorage.app',
    iosBundleId: 'com.example.libraryManagment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQPnZUt5WXvzytPT0MHc5l8DbeYXEXwhw',
    appId: '1:719078466525:web:cefc371fa070431033cc34',
    messagingSenderId: '719078466525',
    projectId: 'dar-almeqdad-manegment',
    authDomain: 'dar-almeqdad-manegment.firebaseapp.com',
    storageBucket: 'dar-almeqdad-manegment.firebasestorage.app',
    measurementId: 'G-LGF0WPJT9L',
  );
}
